import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter, Fira_Mono} from 'next/font/google'
import StoreProvider from '@redux/storeProvider'

const inter = Inter({ subsets: ['latin'] })

const SFMono = localFont({
  src: './SFMono-Regular.woff2',
  display: 'swap',
  variable: '--font-SFMono'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${SFMono.variable}  bg-bg-grad`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
